# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
name: Backend CICD => Agentcis-app
on:
  push:
    branches:
      - 'main'  # ignoring main branch, deployment will be done manually
      - 'develop'
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Display Branch Name on Push
      run: |
        echo "Branch Name: ${{ github.ref_name }}"
        if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
          echo "This push was triggered by a merged Pull Request from ${{ github.event.pull_request.head.ref }} to ${{ github.ref_name }}!"
        else
          echo "Branch Name: ${{ github.ref_name }}"
        fi    

