name: Backend CICD => Agentcis-app

on:
  push:
    branches:
      - 'main' 
      - 'develop'

  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Display Branch Info
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "GitHub Ref Name: ${{ github.ref_name }}"

        if [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.action }}" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
          echo "✅ Pull Request was merged!"
          echo "Source Branch (PR Head): ${{ github.event.pull_request.head.ref }}"
          echo "Target Branch (PR Base): ${{ github.event.pull_request.base.ref }}"
        else
          echo "🔍 Not a merged PR to main — current branch: ${{ github.ref_name }}"
        fi
